language: python
script: ./scripts/build
install:
- sudo apt-get update -qq
- sudo cp -r assets/fonts/* /usr/local/share/fonts/
- sudo fc-cache -f -v
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- sudo pip install python-docx
deploy:
  provider: s3
  access_key_id: AKIAILY5S7AZ77Q4BYBA
  secret_access_key:
    secure: "os6r0tpMbE6e9GBcQn2S/kAPpeQy61ddB5+5N5FGgYv6pm3wL53enTldr1ZAxCp08PXX71mbufGU30WM4lmq4EFT8+zpZhOild30X6ICg8FKaC5Ip99Cp5dB+A+lzxmkF7F1eegxMXgBhfNuNjtM3/97ffyvcCR5xwR2A9Aka4w="
  bucket: dissertate.io
  skip_cleanup: true
  local-dir: build
  on:
    repo: asm-products/Dissertate
    branch: master
